const DATA_GG = {
  id: 'gg',
  name: 'Gestalterische Grundlagen',
  short: 'GG',
  day: 'Montag',
  color: '--gg',

  kannListe: [
    { group: '1. Grundlagen der Gestaltung', items: [
      'Gestaltungsprinzipien wie Kontrast, Harmonie, Balance und Rhythmus erklären',
      'Beschreiben, wie Blickführung in einem Layout funktioniert',
      'Erklären, warum Weißraum wichtig für gutes Design ist',
      'Flächen sinnvoll aufteilen und strukturieren',
      'Layouts übersichtlich und geordnet gestalten',
      'Inhalte nach Wichtigkeit anordnen',
      'Gestalterische Entscheidungen fachlich begründen',
      'Gute und schlechte Layouts analysieren und vergleichen',
      'Raster und Ausrichtungen bewusst einsetzen',
      'Visuelle Hierarchien aufbauen',
    ]},
    { group: '2. Logoentwicklung & Markenauftritt', items: [
      'Erklären, was ein gutes Logo ausmacht',
      'Beschreiben, warum Logos reduziert und einfach gestaltet werden',
      'Zwischen Wortmarke, Bildmarke und Wort-Bild-Marke unterscheiden',
      'Piktogramme und Signets erklären',
      'Logos auf Wiedererkennungswert analysieren',
      'Scribbles und Ideenskizzen erstellen',
      'Mehrere Logoideen entwickeln und variieren',
      'Bildmotive vereinfachen und abstrahieren',
      'Logos digital als Vektorgrafik umsetzen',
      'Erklären, warum Vektorgrafiken für Logos geeignet sind',
      'Passende Dateiformate wie JPG, PNG, PDF oder AI erklären',
      'Begründen, warum bestimmte Formen, Farben oder Symbole verwendet wurden',
    ]},
    { group: '3. Farbe & Farbwirkung', items: [
      'Den Farbkreis erklären',
      'Primär-, Sekundär- und Tertiärfarben unterscheiden',
      'Farbwirkungen beschreiben',
      'Erklären, welche Emotionen Farben auslösen',
      'Farbsymbolik erklären',
      'Passende Farben für bestimmte Zielgruppen auswählen',
      'Farbkontraste erkennen und anwenden',
      'Komplementärfarben erklären',
      'Farbharmonien erstellen',
      'Farbauswahl fachlich begründen',
    ]},
    { group: '4. Typografie', items: [
      'Serif- und Sans-Serif-Schriften unterscheiden',
      'Erklären, welche Wirkung unterschiedliche Schriftarten haben',
      'Schriftgrößen sinnvoll einsetzen',
      'Typografische Hierarchien aufbauen',
      'Lesbarkeit analysieren',
      'Zeilenabstände und Laufweiten anpassen',
      'Passende Schriftkombinationen auswählen',
      'Schriftwirkungen fachlich begründen',
    ]},
    { group: '5. Printdesign', items: [
      'Plakate gestalten',
      'Informationen auf einem Plakat sinnvoll anordnen',
      'Blickführung und Fernwirkung einsetzen',
      'Flyer strukturieren und aufbauen',
      'Einen Wickelfalz erklären und planen',
      'CMYK erklären',
      'Beschnitt und Auflösung erklären',
      'Printprodukte zielgruppengerecht gestalten',
    ]},
    { group: '6. Packaging Design', items: [
      'Verpackungen analysieren',
      'Verpackungsflächen sinnvoll gestalten',
      'Vorder-, Rück- und Unterseite planen',
      'Markenwirkung auf Verpackungen erzeugen',
      'Pflichtinformationen berücksichtigen',
      'Regalwirkung erklären',
      'Mockups erstellen und einsetzen',
    ]},
    { group: '7. Bildbearbeitung & Fotografie', items: [
      'Bilder freistellen',
      'Maskierungen anwenden',
      'Retuschen durchführen',
      'Belichtung erklären (Blende, ISO, Verschlusszeit)',
      'Bildkomposition analysieren',
      'Den Goldenen Schnitt erklären',
      'Frosch- und Vogelperspektive erklären',
    ]},
    { group: '8. Mediengestaltung allgemein', items: [
      'Moodboards erstellen und erklären',
      'Stilrichtungen erkennen und unterscheiden (minimalistisch, retro, futuristisch, handgemacht)',
      'Bildwelten einer Marke analysieren',
      'Storyboards für Filme/Animationen anfertigen',
      'Filmanalyse durchführen (Perspektive, Schnitt, Farbe, Licht)',
      'Visuelle Konzepte entwickeln und präsentieren',
      'Designentscheidungen mit Zielgruppe und Wirkung begründen',
    ]},
  ],

  lernzettel: {
    kompakt: [
      { title: 'Gestaltungsprinzipien', content: 'Kontrast = Unterschied erzeugt Aufmerksamkeit. Harmonie = Elemente passen zusammen. Balance = Gleichgewicht (sym./asym.). Weißraum = bewusste Leerfläche. Blickführung = Auge durch Layout leiten.' },
      { title: 'Logo-Arten', content: 'Wortmarke (nur Text, z.B. Google) · Bildmarke (nur Symbol, z.B. Apple) · Wort-Bild-Marke (beides, z.B. Adidas) · Piktogramm (stark vereinfacht). Gutes Logo = einfach, skalierbar, zeitlos, in S/W und Farbe funktionierend.' },
      { title: 'Farbkreis', content: 'Primär: Rot, Blau, Gelb. Sekundär: Grün, Orange, Violett. Komplementär = gegenüber im Farbkreis = starker Kontrast. Blau = Vertrauen · Rot = Energie · Grün = Natur · Gelb = Freude · Schwarz = Eleganz.' },
      { title: 'Typografie', content: 'Serif = traditionell/seriös. Sans-Serif = modern/klar. Typografische Hierarchie: Überschrift groß → Unterüberschrift mittel → Fließtext klein. Max. 2-3 Schriftarten pro Design.' },
      { title: 'Printdesign', content: 'CMYK (Cyan, Magenta, Yellow, Key/Schwarz) für Druck. RGB für Bildschirm. 300 DPI für Druck nötig. Beschnitt = Rand damit keine weißen Kanten entstehen. Wickelfalz = eine Seite klappt nach innen → Reihenfolge planen!' },
      { title: 'Packaging Design', content: 'Alle Seiten gestalten (auch Unterseite!). Regalwirkung = auffallen, erkennbar sein. Pflichtangaben berücksichtigen. Zielgruppe beachten.' },
      { title: 'Fotografie', content: 'Goldener Schnitt = Motiv nicht mittig. Froschperspektive = mächtig/dominant. Vogelperspektive = klein/übersichtlich. Blende = Tiefenschärfe. ISO = Lichtempfindlichkeit. Verschlusszeit = Bewegungsunschärfe.' },
    ],
    mittel: [
      { title: '1. Gestaltungsprinzipien', content: 'Kontrast erzeugt Aufmerksamkeit und Spannung (hell/dunkel, groß/klein, bunt/neutral). Harmonie bedeutet, dass Elemente zusammenpassen und ruhig wirken. Balance kann symmetrisch (ruhig) oder asymmetrisch (modern/dynamisch) sein. Weißraum ist bewusste Leerfläche – verbessert Lesbarkeit, Fokus und Eleganz. Blickführung steuert das Auge durch Größe, Farbe, Position und Linien.' },
      { title: '2. Logoentwicklung', content: 'Ein gutes Logo ist: einfach, klar, einprägsam, zeitlos, skalierbar. Es muss groß und klein, in Farbe und S/W funktionieren. Logo-Arten: Wortmarke (nur Text), Bildmarke (nur Symbol), Wort-Bild-Marke (beides), Piktogramm (stark reduziert). Entwicklung: Scribbles → Abstraktion/Reduktion → Vektorgrafik (AI/SVG). Dateiformate: AI = Arbeitsdatei, SVG = Web, PDF = Druck, PNG = Transparenz, JPG = Fotos (schlecht für Logos).' },
      { title: '3. Farbe & Farbwirkung', content: 'Farbkreis: Primär (Rot, Blau, Gelb) → Sekundär (Grün, Orange, Violett). Farbwirkungen: Blau = Vertrauen/Sicherheit, Rot = Energie/Aufmerksamkeit, Grün = Natur/Gesundheit, Gelb = Freude/Wärme, Schwarz = Eleganz/Luxus. Komplementärkontrast: gegenüberliegende Farben im Kreis (stark & auffällig). Farbauswahl IMMER begründen: Welche Wirkung? Welche Zielgruppe? Warum passt es zum Produkt?' },
      { title: '4. Typografie', content: 'Serifenschriften = traditionell, seriös, klassisch (z.B. Zeitungen). Sans-Serif = modern, klar, minimalistisch (beliebt im Webdesign). Typografische Hierarchie: Überschrift groß → Unterüberschrift mittel → Fließtext klein. Lesbarkeit hängt ab von: Schriftgröße, Zeilenabstand, Kontrast, Schriftwahl. Max. 2-3 Schriftarten verwenden.' },
      { title: '5. Printdesign', content: 'Plakat: starke Überschrift, große Bilder, wenig Text, klare Blickführung. Flyer: logischer Aufbau, sinnvolle Reihenfolge. Wickelfalz: eine Seite klappt nach innen → Reihenfolge der Seiten genau planen! CMYK für Druck (Cyan, Magenta, Yellow, Schwarz). RGB für Bildschirm. 300 DPI für scharfen Druck. Beschnitt = Rand damit beim Schneiden keine weißen Kanten entstehen.' },
      { title: '6. Packaging Design', content: 'Eine Verpackung soll Aufmerksamkeit erzeugen, das Produkt erklären und die Zielgruppe ansprechen. Alle Seiten gestalten: Vorder-, Rück-, Seitenflächen UND Unterseite (wird oft vergessen!). Regalwirkung = Produkt muss im Regal auffallen und erkennbar sein. Mockups zeigen das Design realistisch auf dem Produkt.' },
      { title: '7. Fotografie & Bildbearbeitung', content: 'Goldener Schnitt: Motiv liegt nicht mittig → wirkt natürlicher und spannender. Perspektiven: Froschperspektive (von unten = mächtig), Vogelperspektive (von oben = übersichtlich). Belichtung: Blende = Lichtmenge & Tiefenschärfe, Verschlusszeit = Bewegung, ISO = Lichtempfindlichkeit (hoch = Rauschen). Bildbearbeitung: Freistellen, Retusche, Maskierung, Ebenen für zerstörungsfreies Arbeiten.' },
    ],
    ausfuehrlich: [
      { title: '1. Grundlagen der Gestaltung', content: 'Gestaltung bedeutet, Informationen visuell so anzuordnen, dass sie verständlich, übersichtlich und ansprechend wirken. Gute Gestaltung lenkt den Blick des Betrachters und vermittelt Gefühle oder Informationen. Ein Design soll Aufmerksamkeit erzeugen, verständlich sein, professionell wirken, zur Zielgruppe passen und eine klare Aussage haben.' },
      { title: 'Kontrast', content: 'Kontrast bedeutet Unterschied. Unterschiede erzeugen Aufmerksamkeit und helfen dem Betrachter, wichtige Inhalte schneller zu erkennen. Beispiele: hell/dunkel, groß/klein, dick/dünn, bunt/neutral. Ein starker Kontrast verbessert die Lesbarkeit und erzeugt Spannung. Beispiel: Weiße Schrift auf schwarzem Hintergrund hat einen starken Hell-Dunkel-Kontrast.' },
      { title: 'Harmonie', content: 'Harmonie bedeutet, dass Elemente gut zusammenpassen. Farben, Formen und Schriftarten sollen miteinander wirken und nicht chaotisch erscheinen. Harmonische Designs wirken ruhig, hochwertig, professionell und angenehm. Zu viele verschiedene Farben oder Schriftarten zerstören oft die Harmonie.' },
      { title: 'Balance & Weißraum', content: 'Balance bedeutet Gleichgewicht im Layout. Symmetrische Balance → ruhig und ordentlich. Asymmetrische Balance → modern und dynamisch. Weißraum sind freie Flächen im Layout. Viele Anfänger machen den Fehler, jedes Stück Fläche füllen zu wollen. Professionelles Design nutzt bewusst freie Bereiche. Weißraum verbessert Lesbarkeit, Struktur, Fokus und Eleganz.' },
      { title: '2. Logoentwicklung', content: 'Ein Logo ist das Erkennungszeichen einer Marke. Es soll dafür sorgen, dass Menschen die Marke wiedererkennen und Vertrauen aufbauen. Ein gutes Logo ist einfach, klar, einprägsam, zeitlos, skalierbar, vielseitig und wiedererkennbar. Es muss groß und klein funktionieren, in Farbe und schwarzweiß. Zu viele Details machen Logos unprofessionell.' },
      { title: 'Logo-Arten', content: 'Wortmarke: Besteht nur aus Schrift (Beispiel: Google). Bildmarke: Besteht nur aus einem Symbol (Beispiel: Apple). Wort-Bild-Marke: Text und Symbol werden kombiniert (Beispiel: Adidas). Piktogramm: Ein stark vereinfachtes grafisches Symbol – reduziert, schnell verständlich, universell erkennbar. Wird oft für Verkehr, Orientierung, Leitsysteme verwendet.' },
      { title: 'Abstraktion & Vektorgrafik', content: 'Logos müssen vereinfacht werden – das nennt man Abstraktion. Ein Objekt wird auf seine wichtigsten Merkmale reduziert. Logos werden als Vektorgrafiken erstellt (bestehen aus Linien, Kurven, Punkten). Vorteile: verlustfrei skalierbar, perfekte Druckqualität, saubere Kanten. Dateiformate: AI (Illustrator-Arbeitsdatei), SVG (Web), PDF (Druck), PNG (Transparenz), JPG (schlecht für Logos).' },
      { title: '3. Farbe & Farbwirkung', content: 'Der Farbkreis zeigt die Beziehung zwischen Farben. Primärfarben: Rot, Blau, Gelb (nicht mischbar). Sekundärfarben entstehen durch Mischung: Grün, Orange, Violett. Farbwirkungen: Blau = Vertrauen, Ruhe, Sicherheit (Banken, Technik). Rot = Energie, Liebe, Aufmerksamkeit (zieht stark an). Grün = Natur, Nachhaltigkeit, Gesundheit. Gelb = freundlich, warm, optimistisch. Schwarz = elegant, modern, luxuriös.' },
      { title: 'Farbkontraste & Harmonie', content: 'Hell-Dunkel-Kontrast: wichtig für Lesbarkeit. Komplementärkontrast: Farben liegen sich im Farbkreis gegenüber (Blau/Orange, Rot/Grün) – wirkt stark und auffällig. Farbharmonie entsteht durch ähnliche Farbtöne, abgestimmte Helligkeiten und passende Sättigung. In der Prüfung IMMER begründen: Warum diese Farbe? Welche Wirkung? Welche Zielgruppe?' },
      { title: '4. Typografie', content: 'Serifenschriften haben kleine Endungen an Buchstaben → traditionell, seriös, klassisch. Sans-Serif = ohne Endungen → modern, klar, minimalistisch, beliebt im Webdesign. Typografische Hierarchie: Überschrift groß, Unterüberschrift mittel, Fließtext klein. Lesbarkeit abhängig von: Schriftgröße, Zeilenabstand, Kontrast, Schriftwahl. Zu viele Schriftarten wirken chaotisch.' },
      { title: '5. Printdesign', content: 'Plakat: muss schnell verstanden werden, muss auffallen. Wichtig: starke Überschrift, große Bilder, wenig Text, gute Blickführung. Flyer: mehr Informationen, logischer Aufbau, gute Seitenstruktur. Wickelfalz: eine Seite wird nach innen gefaltet → Seitenreihenfolge genau planen! CMYK = Farbsystem für Druck (Cyan, Magenta, Yellow, Key/Schwarz). RGB = für Bildschirme. 300 DPI für Druck (zu niedrig = unscharf). Beschnitt = Rand damit keine weißen Kanten beim Schneiden entstehen.' },
      { title: '6. Packaging Design', content: 'Eine Verpackung soll Aufmerksamkeit erzeugen, das Produkt erklären, die Zielgruppe ansprechen und professionell wirken. Alle Bereiche gestalten: Vorderseite, Rückseite, Seitenflächen, Unterseite (wird oft vergessen!). Regalwirkung: Produkte konkurrieren im Regal – müssen auffallen, erkennbar sein und Vertrauen erzeugen. Mockups zeigen das Design realistisch auf einem Produkt bei Präsentationen.' },
      { title: '7. Fotografie & Bildbearbeitung', content: 'Goldener Schnitt: Das Hauptmotiv liegt NICHT genau in der Mitte → wirkt natürlicher, spannender, professioneller. Perspektiven: Froschperspektive (von unten) = mächtig, dominant. Vogelperspektive (von oben) = klein, übersichtlich. Belichtung: Blende = Lichtmenge & Tiefenschärfe. Verschlusszeit = wie lange Licht auf Sensor fällt. ISO = Lichtempfindlichkeit (zu hoch = Bildrauschen). Bildbearbeitung: Freistellen, Retusche, Photomontage, Ebenen (zerstörungsfreies Arbeiten), Masken.' },
      { title: '8. Mediengestaltung allgemein', content: 'Moodboard: visuelle Sammlung aus Bildern, Farben, Texturen, Schriften und Stichworten – zeigt die Stimmung/Richtung eines Projekts. Hilft bei Inspiration, Ideenfindung, Kundenpräsentation. Stilrichtungen: minimalistisch (wenig Elemente, viel Weißraum), retro (alte Optik), futuristisch (technisch, klar), handgemacht (Bleistift, Aquarell). Bildwelten: einheitliche Bildsprache einer Marke (Stil, Farben, Motive, Stimmung). Storyboard: Skizzen-Abfolge für Filme/Werbespots/Animationen – plant Bildausschnitt, Handlung, Übergänge. Filmanalyse: Kameraperspektive, Schnitt, Farbe, Licht, Ton bewusst einsetzen.' },
    ],
  },

  flashcards: [
    { q: 'Was ist Kontrast?', a: 'Unterschiede zwischen Elementen, die Aufmerksamkeit erzeugen. Beispiele: hell/dunkel, groß/klein, bunt/neutral.' },
    { q: 'Was versteht man unter Weißraum?', a: 'Bewusst freigelassene Flächen im Layout. Verbessert Lesbarkeit, Fokus, Struktur und Eleganz.' },
    { q: 'Was ist eine Wortmarke?', a: 'Ein Logo, das nur aus Schrift besteht. Beispiel: Google.' },
    { q: 'Was ist eine Bildmarke?', a: 'Ein Logo, das nur aus einem Symbol besteht. Beispiel: Apple.' },
    { q: 'Was bedeutet Abstraktion beim Logo?', a: 'Das Vereinfachen und Reduzieren eines Objekts auf seine wichtigsten Merkmale.' },
    { q: 'Warum werden Logos als Vektorgrafik erstellt?', a: 'Weil Vektorgrafiken verlustfrei skalierbar sind – sie bleiben in jeder Größe scharf.' },
    { q: 'Was sind die Primärfarben?', a: 'Rot, Blau, Gelb – diese Farben können nicht durch Mischung erzeugt werden.' },
    { q: 'Welche Wirkung hat die Farbe Blau?', a: 'Vertrauen, Ruhe, Sicherheit, Professionalität. Häufig bei Banken und Technikfirmen.' },
    { q: 'Was ist ein Komplementärkontrast?', a: 'Farben, die sich im Farbkreis gegenüberliegen, z.B. Blau & Orange oder Rot & Grün.' },
    { q: 'Was ist der Unterschied zwischen Serifenschrift und Sans-Serif?', a: 'Serif = mit kleinen Endungen (traditionell, seriös). Sans-Serif = ohne Endungen (modern, klar).' },
    { q: 'Was bedeutet typografische Hierarchie?', a: 'Wichtige Inhalte werden größer dargestellt: Überschrift groß → Unterüberschrift mittel → Fließtext klein.' },
    { q: 'Was bedeutet CMYK?', a: 'Cyan, Magenta, Yellow, Key (Schwarz) – das Farbsystem für den Druck.' },
    { q: 'Warum braucht man Beschnitt beim Druck?', a: 'Damit beim Schneiden des Papiers keine weißen Kanten entstehen.' },
    { q: 'Was ist der Goldene Schnitt in der Fotografie?', a: 'Das Hauptmotiv liegt nicht mittig, sondern leicht versetzt – wirkt natürlicher und spannender.' },
    { q: 'Was versteht man unter Regalwirkung bei Verpackungen?', a: 'Die Verpackung muss im Regal zwischen anderen Produkten auffallen, erkennbar sein und Vertrauen erzeugen.' },
    { q: 'Was ist ein Mockup?', a: 'Eine realistische Vorschau, die zeigt wie ein Design auf einem echten Produkt aussieht.' },
    { q: 'Was ist Blickführung?', a: 'Das gezielte Leiten des Auges durch ein Layout durch Größe, Farbe, Position, Linien und Bilder.' },
    { q: 'Was ist ein Piktogramm?', a: 'Ein stark vereinfachtes grafisches Symbol – schnell verständlich und universell erkennbar.' },
    { q: 'Was bedeutet ISO in der Fotografie?', a: 'Die Lichtempfindlichkeit der Kamera. Hoher ISO-Wert = mehr Licht, aber auch mehr Bildrauschen.' },
    { q: 'Was ist Froschperspektive?', a: 'Fotografieren von unten nach oben – lässt das Motiv mächtig und dominant wirken.' },
  ],

  quiz: [
    { type: 'mc', q: 'Was ist eine Wort-Bild-Marke?', options: ['Nur Text', 'Nur Symbol', 'Text und Symbol kombiniert', 'Ein Piktogramm'], correct: 2, explanation: 'Eine Wort-Bild-Marke kombiniert Text und Symbol, z.B. Adidas.' },
    { type: 'mc', q: 'Welches Farbsystem wird für den Druck verwendet?', options: ['RGB', 'CMYK', 'HSL', 'HEX'], correct: 1, explanation: 'CMYK (Cyan, Magenta, Yellow, Key/Schwarz) ist das Farbsystem für den Druck.' },
    { type: 'mc', q: 'Welche Auflösung braucht man für scharfen Druck?', options: ['72 DPI', '150 DPI', '300 DPI', '600 DPI'], correct: 2, explanation: 'Für Druckprodukte werden mindestens 300 DPI (Dots per Inch) benötigt.' },
    { type: 'mc', q: 'Was sind Komplementärfarben?', options: ['Farben, die gleich aussehen', 'Farben, die sich im Farbkreis gegenüberliegen', 'Primärfarben', 'Helle Farben'], correct: 1, explanation: 'Komplementärfarben liegen sich im Farbkreis gegenüber, z.B. Rot und Grün oder Blau und Orange.' },
    { type: 'mc', q: 'Wofür steht "Schöpfungshöhe" bei Logos?', options: ['Die Größe des Logos', 'Das Mindestmaß an Kreativität für Schutz', 'Die Anzahl der Farben', 'Die Schriftgröße'], correct: 1, explanation: 'Schöpfungshöhe beschreibt das Mindestmaß an Kreativität, damit ein Werk urheberrechtlich geschützt ist.' },
    { type: 'mc', q: 'Was ist der Goldene Schnitt?', options: ['Das Motiv liegt genau in der Mitte', 'Das Motiv liegt leicht versetzt von der Mitte', 'Eine Schriftart', 'Ein Druckformat'], correct: 1, explanation: 'Beim Goldenen Schnitt liegt das Hauptmotiv nicht mittig – das wirkt natürlicher und professioneller.' },
    { type: 'mc', q: 'Welche Perspektive lässt ein Motiv mächtig und dominant wirken?', options: ['Vogelperspektive', 'Normalperspektive', 'Froschperspektive', 'Zentralperspektive'], correct: 2, explanation: 'Die Froschperspektive (von unten fotografiert) lässt Motive mächtig und dominant wirken.' },
    { type: 'mc', q: 'Warum müssen Logos als Vektorgrafik erstellt werden?', options: ['Weil sie kleiner sind', 'Weil sie verlustfrei skalierbar sind', 'Weil sie günstiger sind', 'Weil sie transparenter sind'], correct: 1, explanation: 'Vektorgrafiken bestehen aus mathematischen Formen und können ohne Qualitätsverlust beliebig vergrößert werden.' },
    { type: 'open', q: 'Erkläre den Unterschied zwischen Weißraum und einem Gestaltungsfehler durch zu viel Leere. Wann ist Weißraum gut, wann schlecht?', model: 'Weißraum ist gut, wenn er bewusst eingesetzt wird, um Inhalte zu gruppieren, Lesbarkeit zu verbessern und Eleganz zu erzeugen. Zu viel Leere ist ein Fehler, wenn das Layout unvollständig oder unfertig wirkt und wichtige Informationen fehlen. Der Unterschied liegt in der Absicht und dem Gesamteindruck.' },
    { type: 'open', q: 'Beschreibe, wie du ein Logo für eine umweltfreundliche Bio-Marke gestalten würdest. Begründe deine Farbwahl, Schrift und Form.', model: 'Beispiel-Begründung: Ich würde Grün als Hauptfarbe wählen, da Grün Natur, Nachhaltigkeit und Gesundheit symbolisiert. Als Schrift würde ich eine serifenlose, organisch wirkende Schrift wählen, die modern und vertrauenswürdig wirkt. Die Form wäre ein reduziertes Blatt oder Pflanzensymbol als Piktogramm, das einfach und sofort erkennbar ist.' },
  ],

  aufgaben: [
    {
      title: 'Logo-Entwicklung: Café "Grüne Pause"',
      points: '20 Punkte',
      question: 'Entwickle ein Logo für das Café "Grüne Pause". Das Café ist ein nachhaltiges Bio-Café in der Stadtmitte, das junge, umweltbewusste Kunden ansprechen möchte.\n\n1. Erstelle mindestens 3 verschiedene Scribbles/Ideenskizzen.\n2. Wähle einen Entwurf aus und begründe deine Wahl.\n3. Beschreibe deine Farbwahl und ihre Wirkung.\n4. Erkläre, welchen Logo-Typ du gewählt hast (Wortmarke, Bildmarke, Wort-Bild-Marke).',
      model: '1. Scribbles: z.B. stilisiertes Blatt als Buchstabe, Kaffeetasse mit Pflanzen-Element, typografische Wortmarke.\n2. Wahl begründen: z.B. Wort-Bild-Marke, weil sie sowohl den Namen als auch einen visuellen Anker hat.\n3. Farbwahl: Grün = Natur und Nachhaltigkeit, ergänzt durch Erdtöne (Braun/Beige) für Wärme und Café-Atmosphäre.\n4. Logo-Typ: Wort-Bild-Marke mit Schrift und Pflanzensymbol.'
    },
    {
      title: 'Farbwirkung analysieren',
      points: '15 Punkte',
      question: 'Du siehst zwei Produktverpackungen für Energydrinks:\n• Verpackung A: Schwarz mit goldenen Akzenten\n• Verpackung B: Neongrün mit weißer Schrift\n\n1. Beschreibe die Wirkung beider Farbkombinationen.\n2. Welche Zielgruppe spricht welche Verpackung an? Begründe.\n3. Welche Verpackung würdest du für einen Premium-Energydrink wählen und warum?',
      model: '1. A (Schwarz/Gold): elegant, luxuriös, exklusiv, hochwertig. B (Neongrün/Weiß): energetisch, auffällig, jung, frisch, sportlich.\n2. A spricht ältere, einkommensstärkere Kunden an. B spricht junge, sportliche Menschen an.\n3. Für Premium würde Verpackung A gewählt, da Schwarz und Gold Luxus und Exklusivität signalisieren.'
    },
    {
      title: 'Plakatgestaltung: Schulveranstaltung',
      points: '25 Punkte',
      question: 'Gestalte (beschreibe und skizziere) ein Plakat für einen Schulfotowettbewerb.\n\n1. Welche Informationen müssen auf das Plakat?\n2. Wie setzt du Blickführung ein?\n3. Welche Schriften und Farben würdest du verwenden?\n4. Erkläre deinen gestalterischen Aufbau.',
      model: '1. Pflichtinfos: Titel, Datum, Ort, Teilnahmebedingungen, Kontakt/Website.\n2. Blickführung: Große Überschrift oben zieht den Blick zuerst an → Bild in der Mitte hält Interesse → Details unten.\n3. Schriften: serifenlose Schrift für Überschrift (modern), Serifenschrift für Details möglich.\n4. Aufbau: starkes zentrales Bild, kurzer Text, viel Weißraum, klare Hierarchie.'
    },
    {
      title: 'Packaging Design: Schokolade',
      points: '20 Punkte',
      question: 'Du sollst eine Schokoladenverpackung für die Zielgruppe "Kinder (6-12 Jahre)" gestalten (beschreiben).\n\n1. Welche Farben wählst du und warum?\n2. Welche Schriftart passt?\n3. Welche Pflichtangaben müssen auf der Verpackung sein?\n4. Was muss auf der Unterseite stehen?',
      model: '1. Farben: kräftige, bunte Farben (Gelb, Rot, Orange) – wirken fröhlich, energetisch und kindgerecht.\n2. Schrift: runde, verspielt wirkende Schrift ohne scharfe Kanten – wirkt freundlich und kindgerecht.\n3. Pflichtangaben: Zutatenliste, Nährwertangaben, Gewicht, Hersteller, Mindesthaltbarkeit, Allergene.\n4. Unterseite: Barcode, Hersteller/Importeur-Adresse, Recycling-Symbol.'
    },
    {
      title: 'Typografie: Fehleranalyse',
      points: '10 Punkte',
      question: 'Ein Design verwendet 5 verschiedene Schriftarten, davon 2 Serifenschriften und 3 Sans-Serif-Schriften in unterschiedlichen Farben.\n\n1. Was ist das Problem mit diesem Design?\n2. Wie würdest du es verbessern?\n3. Erkläre die Bedeutung von typografischer Hierarchie.',
      model: '1. Problem: Zu viele Schriftarten wirken chaotisch, unruhig und unprofessionell. Keine klare Hierarchie erkennbar.\n2. Verbesserung: Maximal 2 Schriftarten – eine für Überschriften, eine für Fließtext. Klare Hierarchie durch Größenunterschiede.\n3. Typografische Hierarchie: Wichtige Inhalte werden größer/auffälliger dargestellt → Betrachter erkennt sofort die Struktur.'
    },
    {
      title: 'Bildkomposition: Goldener Schnitt',
      points: '10 Punkte',
      question: 'Erkläre anhand eines selbst gewählten Beispiels, wie du den Goldenen Schnitt in der Fotografie anwenden würdest.\n\n1. Beschreibe das Bild (Motiv, Setting).\n2. Wo würdest du das Hauptmotiv positionieren?\n3. Welche Wirkung hat das auf den Betrachter?',
      model: '1. Beispiel: Porträtfoto einer Person in einem Park.\n2. Die Person würde nicht in der Bildmitte stehen, sondern auf einem der vier Kreuzungspunkte des gedachten Dritteln-Rasters (linkes oder rechtes Drittel).\n3. Wirkung: Das Bild wirkt dynamischer, natürlicher und professioneller als bei zentrierter Komposition. Der Blick hat Raum zum Wandern.'
    },
    {
      title: 'Logo-Analyse: Bekannte Marken',
      points: '15 Punkte',
      question: 'Analysiere das Logo von Apple:\n\n1. Zu welchem Logo-Typ gehört es?\n2. Welche Wirkung hat die Farbgebung?\n3. Was macht dieses Logo zu einem guten Logo?\n4. Warum ist Abstraktion hier wichtig?',
      model: '1. Logo-Typ: Bildmarke (nur Symbol, kein Text).\n2. Farbgebung: Silber/Schwarz/Weiß → elegant, modern, premium, minimalistisch.\n3. Gutes Logo: einfach, sofort erkennbar, funktioniert in jeder Größe, zeitlos, einprägsam.\n4. Abstraktion: Ein stark vereinfachter Apfel ist viel einprägsamer als eine realistische Abbildung. Das reduzierte Symbol ist universell erkennbar.'
    },
  ],
};
